In [ ]:
# 1. Abbiamo una lista di liste. Che tipo di struttura dati o matematica potrebbe rappresentare? Notate che tutte le liste "interne" sono della stessa dimensione.
#Come facciamo per accedere ad un elemento in particolare?
mat = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]]
#La variabile mat rappresenta una matrice o un dataset

#Per richiamare un elmento bisogna utilizzare il nome della variabile seguito da due coppie di parentesi quadre dentro alla quale si indica la lista in cui è contenuto l'elemento e la posizione dello stesso all'interno della lista.
#Esempio di richiamo del valore "11", contenuto nella lista alla posizione "1" nella lista alla posizione "2"
mat[2][1]

In [ ]:
# 2. Trasformiamo la lista dell'esercizio precendente ini un array NUmPy.
import numpy as np
mat = [[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]]
mat_ny = np.array(mat)
# Come facciamo per accedere ai singoli elementi?
# Si può accedere utilizzando il metodo precedente
mat_ny[2][1]


In [9]:
# 3. Abbiamo il seguente array NumPy.
import numpy as np
linear_data = np.array([x for x in range(27)])
# Lo ridimensioniamo tramite il metodo .reshape().
reshaped_data = linear_data.reshape(3,3,3)
#Quante dimensioni ha il nuovo array?
print(reshaped_data.shape)
#Come facciamo per accedere ai singoli elementi?
print(reshaped_data)
#Nome variabile e parentesi quadre a seguire per indicare le posizioni dell'elemento che si vuole richiamare
reshaped_data[1][0][2]

(3, 3, 3)
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


11

In [ ]:
# 4. Abbiamo un territorio diviso in quattro quadranti; in ognuno di essi c'è uno store.
# Vogliamom contare quanti clienti vengono serviti dai diversi store: creiamo una struttura dati adeguata con un array NUmPy, dove il conteggio di ogni store parta da zero.
import numpy as np
import random
quadranti = np.array(["UL","UR","LL","RR"])
clienti = np.array([0,0,0,0])
for x in range(100):
    pos = random.randint(0,3)
    clienti[pos] += 1
for el in range(len(clienti)):
    print(str(quadranti[el]) + " : " +str(clienti[el]))
#Alla fine, che valore ha lo store UR? E lo store LL?
print("\nLo store " + str(quadranti[1]) + " ha " + str(clienti[1]) + " clienti e lo store " + str(quadranti[2]) + " ha " + str(clienti[2])+ " clienti.")

#Quale store ja più di 25 clienti? Quanti clienti hanno avuto di preciso questi store?
print("Store con più di 25 clienti:")
for el in range(len(quadranti)): 
    if clienti[el] > 25 : print(str(quadranti[el]) +  " ha " + str(clienti[el]) + " clienti.")
    

In [ ]:
# 4. 3/3 Ripetiamo la traccia precedente ma stavolta abbiamo nove quadranti e 200 iterazioni.
import numpy as np
import random
quadranti = np.array(["UL","UC","UR","ML","MC","MR","LL","LC","LR"])
clienti = np.array([0,0,0,0,0,0,0,0,0])
for x in range(200):
    pos = random.randint(0,8)
    clienti[pos] += 1
print("\nPer questo anno la situazione è la seguente:")
for el in range(len(clienti)):
    print(str(quadranti[el]) + " : " +str(clienti[el]))
# L'anno prossimo ci aspettiamo 4 volte i valori appena ottenuti; simuliamo velocemente il tutto e stampiamo il risultato
for el in range(len(clienti)):
    clienti[el] *=4
print("\nPer il prossimo anno la situazione attesa è la seguente:")
for el in range(len(clienti)):
    print(str(quadranti[el]) + " : " +str(clienti[el]))

In [ ]:
# 5. Chiediamo all'utente di inserire un numero, dividiamolo per 5 e poi stampiamo a il risultato a video. Gestiamo correttamente le eccezioni nel caso in cui l'utente immetta un input errato.
while True:                                                                                                                 
    print("Inserisci il numero da dividere per 5:")
    try:    
        num = int(input())
    except:print("Hai inserito un valore non valido: riprova.")
    else :
        print(num/5)
        break

In [ ]:
# 6. In una catena di montaggio abbiamo una struttura metallica di 28.75 cm di lunghezza: per assicurarne la stabilità. è necessario inserire 15 rivetti dei quali uno all'inizio ed uno alla fine e tutti quanti separati dalla
# stessa distanza. Come possiamo calcolare i punti esatti in cui inserire i rivetti tramite NumPy?
lung_strutt = 28.75
num_rivetti = 15
dist = lung_strutt/(num_rivetti-2)
print("I rivetti vanno posizionati ogni: " + str(round(dist,2)) + " cm.")

In [ ]:
# 7. Scarichiamo l'Iris Dataset.
# Leggiamo il file e carichiamo in un Dataframe mediante pd.read_csv() senza utilizzare altri parametri
import pandas as pd
data_set = pd.read_csv("iris.data")
# Stampiamo le prime 5 righe
print(data_set.head())

In [ ]:
# Stampiamo i nomi delle colonne: sono corretti?
data_set.columns #Ovviamente no

In [ ]:
# Leggiamo  il file e carichiamo in una DataFrame aggiungendo i nomi di colonna come parametro
data_set = pd.read_csv("iris.data",header=None,names=['sepal length in cm','sepal width in cm','petal length in cm','petal width in cm','class'])
#Stampiamo le prime cinque righe
data_set.head()

In [ ]:
# E le ultime 10
data_set.tail(10)

In [ ]:
# Stampiamo un riepilogo dei descrittori statistici del dataset
data_set.describe()

In [ ]:
# 8. Tra i vari dataset, ce n'è uno che contiene diverse qualità di vini e le misure di dioverse proprietà organolettiche, wine.csv; Leggiamo quindi il dataset e visualizziamo le prime e le ultime righe
import pandas as pd
wine = pd.read_csv("beginner_datasets/wine.csv")
wine

In [ ]:
# Leggiamo nuovamente il dataset ma stavolta considerando solo le ultime 6 colonne ricordandoci che in totale il dataset ha 13 colonne
wine=pd.read_csv("beginner_datasets/wine.csv",usecols=[x for x in range(7,13,1)])
wine

In [ ]:
# Visualizziamo un recoconto dei descrittori statistici di questa versione
wine.describe()

In [6]:
# 10. Abbiamo la seguente matrice. Creiamo un ndarray con gli stessi valori
import numpy as np
arr_matrix = np.matrix([(1,1,1,1),(5,1,1,1),(20,-4,0,42)])
arr_ = np.array([el for el in arr_matrix])
arr_ = np.ndarray.reshape(arr_,(1,12))
arr_


array([[ 1,  1,  1,  1,  5,  1,  1,  1, 20, -4,  0, 42]])